sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm i react-native@0.44.0
  - npm i react@0.16.0-alpha.3
script:
  - npm run test:cover
after_success:
  - npm run test:report
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
os:
  - osx
